name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish win32-app-container-tokens
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: win32-app-container-tokens

        buildSteps:
          - script: npm ci
            displayName: Install dependencies

          - script: npm run build
            displayName: Build

        testPlatforms:
          - name: Windows
            nodeVersions:
              - 20.x

        testSteps:
          - script: npm ci
            displayName: Install dependencies

          - script: npm test
            displayName: Test

        rustTargets: aarch64-pc-windows-msvc x86_64-pc-windows-msvc
        apiScanSoftwareName: "vscode-win32-app-container-tokens"
        apiScanSoftwareVersion: "0.1"
        publishPackage: ${{ parameters.publishPackage }}
        packagePlatform: Windows
